#!/bin/sh -e

openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -batch \
  -keyout /etc/lighttpd-server.pem \
  -out /etc/lighttpd-server.pem > /dev/null 2>&1

mkdir /www
tee /www/index.html > /dev/null <<EOF
<html>
  <body>
    <table>
      <tr>
        <td><code><b>Hostname</b></code></td>
        <td><code>$(hostname)</code></td>
      </tr>
      <tr>
        <td><code><b>Container</b></code></td>
        <td><code>$(cat /proc/self/cgroup | grep 'cpu:/' | sed 's/\([0-9]\):cpu:\/docker\///g')</code></td>
      </tr>
      <tr>
        <td><code><b>Started</b></code></td>
        <td><code>$(date)</code></td>
      </tr>
    </table>
  </body>
</html>
EOF

lighttpd -v
exec lighttpd -D -f /etc/lighttpd.conf
